#include <iostream>

using namespace std;

class Car {
private:
    string brand;
    string model;
    double rentalPrice;
    bool isAvailable;
    double totalRevenue;

public:
    Car() {
        brand = "Unknown";
        model = "Generic";
        rentalPrice = 0.0;
        isAvailable = true;
        totalRevenue = 0.0;
    }

    Car(string newBrand, string newModel, double newPrice, bool availability) {
        brand = newBrand;
        model = newModel;
        rentalPrice = newPrice;
        isAvailable = availability;
        totalRevenue = 0.0;
    }

    Car(const Car &other) {
        brand = other.brand;
        model = other.model;
        rentalPrice = other.rentalPrice;
        isAvailable = other.isAvailable;
        totalRevenue = other.totalRevenue;
        cout << "Copy Constructor: A copy of " << brand << " " << model << " has been created.\n";
    }

    ~Car() {
        cout << "Destructor: Car " << brand << " " << model << " is being removed from memory.\n";
    }

    void updateDetails(string newBrand, string newModel, double newPrice) {
        brand = newBrand;
        model = newModel;
        rentalPrice = newPrice;
        cout << "Car details updated successfully.\n";
    }

    bool checkAvailability() const {
        return isAvailable;
    }

    void applyDiscount(int rentalDays, double &finalPrice) {
        if (rentalDays > 10) {
            finalPrice *= 0.90;
        } else if (rentalDays > 5) {
            finalPrice *= 0.95;
        }
    }

    void rentCar(int rentalDays) {
        if (!isAvailable) {
            cout << "Sorry, the car is already rented.\n";
            return;
        }

        double finalPrice = rentalPrice;
        applyDiscount(rentalDays, finalPrice);
        double rentalCost = finalPrice * rentalDays;

        this->totalRevenue += rentalCost;
        this->isAvailable = false;

        cout << "Car rented successfully for " << rentalDays << " days!\n";
        cout << "Total rental cost: $" << rentalCost << "\n";
    }

    void returnCar() {
        isAvailable = true;
        cout << "Car has been returned and is now available for rent.\n";
    }

    void displayDetails() const {
        cout << "Brand: " << brand << "\nModel: " << model
             << "\nRental Price: $" << rentalPrice 
             << "\nAvailable: " << (isAvailable ? "Yes" : "No") 
             << "\nTotal Revenue: $" << totalRevenue << "\n";
    }

    void displayRevenue() const {
        cout << "Total Revenue generated by " << brand << " " << model << ": $" << totalRevenue << "\n";
    }
};

int main() {
    Car car1("Toyota", "Corolla", 50.0, true);

    car1.displayDetails();
    car1.rentCar(7);
    car1.displayRevenue();

    car1.returnCar();
    car1.rentCar(3);
    car1.displayRevenue();

    return 0;
}
